### ISSUE TITLE
注册账号类型转换异常

### ISSUE THREAD

**Issue by adzcsx2** [easemob/easemob-im-app-server#9]
2022-02-14 10:24:54.063 22215-22215/com.hyphenate.easeim W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at android.os.BaseBundle.getInt(BaseBundle.java:1036)
        at android.os.BaseBundle.getInt(BaseBundle.java:1018)
        at com.hyphenate.push.EMPushConfig$Builder.enableVivoPush(Unknown Source:27)
        at com.hyphenate.push.EMPushConfig$Builder.<init>(Unknown Source:56)
        at com.hyphenate.chat.EMClient.init(Unknown Source:119)
        at com.hyphenate.easeui.EaseIM.init(EaseIM.java:94)
        at com.hyphenate.easeim.DemoHelper.initSDK(DemoHelper.java:193)
        at com.hyphenate.easeim.DemoHelper.init(DemoHelper.java:135)
        at com.hyphenate.easeim.common.repositories.EMClientRepository$2.createCall(EMClientRepository.java:88)
        at com.hyphenate.easeim.common.repositories.NetworkOnlyResource.fetchFromNetwork(NetworkOnlyResource.java:47)
        at com.hyphenate.easeim.common.repositories.NetworkOnlyResource.init(NetworkOnlyResource.java:40)
        at com.hyphenate.easeim.common.repositories.NetworkOnlyResource.<init>(NetworkOnlyResource.java:28)
        at com.hyphenate.easeim.common.repositories.EMClientRepository$2.<init>(EMClientRepository.java:82)
        at com.hyphenate.easeim.common.repositories.EMClientRepository.registerToHx(EMClientRepository.java:82)
        at com.hyphenate.easeim.section.login.viewmodels.LoginViewModel.register(LoginViewModel.java:48)
        at com.hyphenate.easeim.section.login.fragment.RegisterFragment.registerToHx(RegisterFragment.java:169)
        at com.hyphenate.easeim.section.login.fragment.RegisterFragment.onClick(RegisterFragment.java:157)
        at android.view.View.performClick(View.java:6603)
        at android.view.View.performClickInternal(View.java:6576)
        at android.view.View.access$3100(View.java:780)
        at android.view.View$PerformClick.run(View.java:26088)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by adzcsx2** [comment]
发错地方
